### ISSUE TITLE
如何指定其他类别训练

### ISSUE THREAD

**Issue by Hxiangdou** [dragonfly606/MonoCD#9]
我尝试指定

```
DATASETS:
  DETECT_CLASSES: ("Car", )
  TRAIN: ("kitti_train",)
  TEST: ("kitti_test",)
  TRAIN_SPLIT: "train"
  TEST_SPLIT: "val"
```

为
```
DATASETS:
  DETECT_CLASSES: ("Pedestrian", )
  TRAIN: ("kitti_train",)
  TEST: ("kitti_test",)
  TRAIN_SPLIT: "train"
  TEST_SPLIT: "val"
```
但是会报错
